FROM golang:1.25.5-bookworm

WORKDIR /app

COPY go.mod go.sum .

RUN  --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=bind,source=go.sum,target=go.sum \
    --mount=type=bind,source=go.mod,target=go.mod \
    go mod download

ENV GOCACHE=/root/.cache/go-build

COPY . .

RUN --mount=type=cache,target=/go/pkg/mod/ \
    --mount=type=cache,target="/root/.cache/go-build" \
    --mount=type=bind,target=. \
    go build -o /main .

EXPOSE 8080

ENTRYPOINT ["/main"]
